# Place this file at:
#    Linux:    ~/.local/share/WaniKaniTUI/config.yml
#    Windows:  %LOCALAPPDATA%\WaniKaniTUI\config.yml

# Maximum number of review items the user is working on at once.
buffer_size: 5
# Font used for multiline CJK rendering
cjk_font_path: "/absolute/path/to/a/JP_font.ttf"
