# Place this file at:
#    Linux:    ~/.local/share/WaniKaniTUI/config.yml
#    Windows:  %LOCALAPPDATA%\WaniKaniTUI\config.yml

# Maximum number of review items the user is working on at once.
buffer_size: 5

# Font used for multiline CJK rendering
cjk_font_path: "/absolute/path/to/a/JP_font.ttf"

# Renderes CJK twice as tall while perserving width.
# - Improves resoluition on terminals with 0 line separartion.
no_line_spacing_correction: False

# Sets an upper bound on the size of CJK characters in lines.
# - Below 10, the characters become significantly distorted.
# - Below 5, the characters are illegible.
max_char_height: 50

# Switches CJK pane to use dark text
dark_cjk: False

# Sets default color group
# - Available: default, wanikani
theme: "default"

# Defines custom colors
# - if partially defined, rest will be filled from base_colors group
colors:
  background: "#282828"
  foreground: "#eeeeee"
  radical: "#56638a"
  kanji: "#9c4644"
  vocab: "#58896f"
  progress: "#a97e42"
