# Place this file at:
#    Linux:    ~/.local/share/WaniKaniTUI/config.yml
#    Windows:  %LOCALAPPDATA%\WaniKaniTUI\config.yml

# Maximum number of review items the user is working on at once.
review_buffer_size: 5

# Amount of items in each lesson block.
lesson_buffer_size: 5

# Typo leniency for meaning questions
# 0 - everything passes
# 1 - only exact matches pass (case insensitive)
typo_strictness: 0.9

# Font used for multiline CJK rendering
cjk_font_path: "/absolute/path/to/a/JP_font.ttf"

# Renderes CJK twice as tall while perserving width.
# - Improves resoluition on terminals with 0 line separartion.
no_line_spacing_correction: False

# Sets an upper bound on the size of CJK characters in lines.
# - Min. 8, anything bellow will disable the braille font rendering
max_char_height: 50

# Switches CJK pane to use background color for text
invert_cjk_color: False

# Inverts progress bar bg
invert_progress_bar_bg: False

# Sets default color group
# - Available: elementary_dark, wanikani
theme: "elementary_dark"

# Defines custom colors
# - if partially defined, rest will be filled from theme group
colors:
  background: "#282828"
  foreground: "#eeeeee"
  radical: "#56638a"
  kanji: "#9c4644"
  vocab: "#58896f"
  progress: "#a97e42"
  incorrect: "#9c4644"
  highlight: "#c29354"
