background: "#282828"
foreground: "#eeeeee"

radical: "#56638a"
kanji: "#9c4644"
vocab: "#58896f"

#apprentice: "#47454e"
#guru: "#605c74"
#master: "#9A815d"
#enlightened: "#934c3f"
#burned: "#303030"

#lesson: "#9c4644"
#review: "#56638a"
#correct: "#58896f"
#incorrect: "#9c4644"

progress: "#a97e42"
